repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
    -   id: check-added-large-files
    -   id: check-toml
    -   id: check-yaml
    -   id: pretty-format-json
    -   id: name-tests-test
        args: [--pytest-test-first]
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        language_version: python3.10
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        exclude: ^(docs/|tests/)
        additional_dependencies:
          - flake8-black>=0.1.1
        language_version: python3.10
