name: linting and unit-tests

on: [push, pull_request, workflow_dispatch]

jobs:
  prepare:
    name: python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.10", "3.x"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'
      - name:   "Update pip"
        run:    pip install --upgrade pip
      - name:   "Style guide enforcement: flake8"
        run:    |
                pip install flake8
                flake8 ./src
        shell:  bash -l {0}
      - name:   "Style guide enforcement: black"
        run:    |
                pip install black
                black src --check --verbose
        shell:  bash -l {0}
      - name:   Install requirements
        shell:  bash -l {0}
        run:    |
                pip install -e .
                pip install -r requirements.txt
                pip install -r requirements-dev.txt
      - name:   "Static type checking: mypy"
        run:    |
                pip install mypy
                mypy
        shell:  bash -l {0}
      - name:   Run unit-tests
        run:    python -m unittest discover
        shell:  bash -l {0}
      - name:   Build python package
        run:    |
                pip install build
                git fetch --prune --unshallow
                git fetch --depth=1 origin +refs/tags/*:refs/tags/*
                python -m build
      - name:   "Sphinx: build"
        run:    sphinx-build docs/source _build
      - name:   "Sphinx: deploy"
        uses:   peaceiris/actions-gh-pages@v3
        if:     ${{ runner.os == 'Linux' && matrix.python-version == '3.10' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token:   ${{ secrets.GITHUB_TOKEN }}
          publish_dir:    _build/
          force_orphan:   true
