name: linting and unit-tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:
    branches:
      - master
      - develop

jobs:
  tests:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      -   name: install requirements
          shell: bash -l {0}
          run: |
            pip install --upgrade pip
            pip install --editable bpod
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
      - run: flake8
        shell: bash -l {0}
      - run: python -m unittest discover
        shell: bash -l {0}
      - run: mypy
        shell: bash -l {0}
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "src/*.py"
          jupyter: false
          version: "~= 22.0"
